[package]
name = "aoc_2024_13"
version = "0.1.0"
edition = "2021"

[[bin]]
name="part1"

[dependencies]
rayon = "1.10.0"
regex = "1.11.1"
ndarray = "0.14"
ndarray-linalg = { version = "0.13", features = ["openblas-static"] }
